title: "OWASP BLADE: Business Logic Attack Definition Framework"
locale: "en-US"
description: "The OWSAP Business Logic Attack Definition (BLADE) Framework, is an open-source knowledge-base created to help cybersecurity professionals fight cyber threats."
#tagline: "The BLADE framework for Bot attacks"
remote_theme: "mmistakes/minimal-mistakes@4.23.0"

owasp: "/assets/images/Logo_owasp_black.svg"
logo: "/assets/images/Netblade_black_logo.svg"
logo_footer: "/assets/images/Netblade_black_logo.svg"
masthead_title: false
breadcrumbs: true
exclude:
  - docker-compose.yml
  - README.md

search: true

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag

atom_feed:
  hide: true

collections:
  pages:
    output: true
  phases:
    output: true
  tactics:
    output: true
  techniques:
    output: true
  blogs:
    output: false
  ext-references:
    output: false  
  videos:
    output: false
  kill-chains:
      output: true
  reports:
      output: false
 
 # Site Footer
footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/netblade-framework"
    # - label: "Linkedin"
    #   icon: "fab fa-fw fa-linkedin"
    #   url: "https://instagram.com"
